spring.application.name=JobTracker

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Krishna@gokii047
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Swagger
enable.swagger.plugin=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
springfox.documentation.swagger-ui.enabled=true

# JWT
jwt.secret=jobTrackerSecretKey123456789abcdefghijklmnopqrstuvwxyz
jwt.expiration=86400000

# Server Port
server.port=8081

# Exclude mail autoconfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
